version: "2"

services:

  database:
    image: mysql
    restart: always
    container_name: db_container
    environment:
      MYSQL_ROOT_PASSWORD: root
#      MYSQL_USER: root
      MYSQL_DATABASE: bugtracker
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"